// svelte-simple-icons licensed under MIT https://github.com/icons-pack/svelte-simple-icons

export { default as Amazonaws } from './Amazonaws.svelte';
export { default as ConstructThree } from './ConstructThree.svelte';
export { default as CssThree } from './CssThree.svelte';
export { default as Express } from './Express.svelte';
export { default as Git } from './Git.svelte';
export { default as Html5 } from './Html5.svelte';
export { default as Javascript } from './Javascript.svelte';
export { default as Mongodb } from './Mongodb.svelte';
export { default as NodeDotJs } from './NodeDotJs.svelte';
export { default as Notion } from './Notion.svelte';
export { default as React } from './React.svelte';
export { default as Redux } from './Redux.svelte';
export { default as Svelte } from './Svelte.svelte';
export { default as Email } from './Email.svelte';
export { default as Linkedin } from './Linkedin.svelte';
export { default as Github } from './Github.svelte';
export { default as Sqlite } from './Sqlite.svelte';
export { default as Jquery } from './Jquery.svelte';
export { default as Figma } from './Figma.svelte';
export { default as Typescript } from './Typescript.svelte';
export { default as Mysql } from './Mysql.svelte';
export { default as Postgresql } from './Postgresql.svelte';
export { default as Android } from './Android.svelte';
export { default as Apple } from './Apple.svelte';
export { default as Json } from './Json.svelte';
export { default as Firebase } from './Firebase.svelte';
export { default as Supabase } from './Supabase.svelte';
